intranet/intranet/connection_on_device/urls.py
from django.urls import path

from connection_on_device import views
from models_device.views import DeviceView

urlpatterns = [
	path('', DeviceView.as_view(), name='dev_list'),
    path('<int:id_dev>/del_connection', views.DelConnection.as_view(), name='del_connection'),
    path('<int:id_dev>/edit_connection/<int:id_con>', views.EditConnection.as_view(), name='edit_connection'),
	path('<int:id_dev>/path', views.path_to, name='path_to_dev'),
	path('<int:id_dev>/add_connection', views.AddConnection.as_view(), name='add_connection'),
	path('<int:id_dev>/all_connection', views.all_connection, name='all_connection'),
	path('<int:id_dev>/', views.on_device, name='connections_on_dev'),
]

intranet/intranet/intranet/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from models_device.views import DeviceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(),
    {'template_name': "login.html",
    'extra_context': {}}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', DeviceView.as_view(), name='device'),
    path('device/', include('models_device.urls')),
    path('connection/', include('connection_on_device.urls')),
]

intranet/intranet/cities/models.py
from django.db import models

# Create your models here.

REGIONS = (
	(1, 'Spb'),
	(2, 'Region2'),
	(3, 'Region3'),
	(4, 'Region4'),
	(5, 'Region5'),
	)


class Cities(models.Model):

    city = models.CharField(max_length=30, help_text='Город')
    city_prefix = models.CharField(max_length=10, help_text='Префикс в мнемокоде')
    region = models.IntegerField(choices=REGIONS)
    comment = models.TextField(blank=True)


    def __str__(self):
        _text = f"{REGIONS[self.region-1][1]} {self.city} ({self.city_prefix});  {self.comment}"
        return _text

    def get_reg_id(region: str):
        for _id, _reg in REGIONS:
            if _reg == region:
                return _id

    def all_regions():
        regions = []
        for _reg in REGIONS:
            regions.append(_reg[1])
        return regions


    class Meta:
        verbose_name = 'Город'
        verbose_name_plural = 'Города'

intranet/intranet/connection_on_device/models.py
from django.db import models

# Create your models here.
from models_device.models import Device

class ConnectionOnDevice(models.Model):

    id_dev = models.ForeignKey(Device, on_delete=models.CASCADE, 
        help_text='ID оборудования, к которому подключен клиент/устройство')
    port = models.CharField(max_length=10, help_text='Порт подключения')
    connected = models.CharField(max_length=40, help_text='Что подключено к порту')
    vlan = models.CharField(max_length=5, default='Null', help_text='vlan клиента, если есть')
    ip_client = models.TextField(blank=True, verbose_name='IP клиента', help_text='IP/сети выделенные клиенту через ";"')
    comment = models.TextField(blank=True, help_text='Комментарий')
    date = models.DateTimeField(auto_now_add=True, help_text='Дата добавления')
    update = models.DateTimeField(auto_now=True, help_text='Дата изменения')


    def __str__(self):
        _text = f"{self.id_dev.city.city} --> {self.connected} on {self.id_dev.ip} port {self.port};  {self.comment}"
        return _text

    class Meta:
    	verbose_name = "Подключенное оборудование/клиенты"
    	verbose_name_plural = "Подключенное оборудование/клиенты"

intranet/intranet/connection_on_device/forms.py
from django import forms


from connection_on_device.models import ConnectionOnDevice


class AddConnectionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['port'].widget.attrs.update({'class': 'form-control'})
        self.fields['connected'].widget.attrs.update({'class': 'form-control'})
        self.fields['vlan'].widget.attrs.update({'class': 'form-control'})
        self.fields['ip_client'].widget.attrs.update({'class': 'form-control'}, cols='20', rows='4')
        self.fields['comment'].widget.attrs.update({'class': 'form-control'}, cols='20', rows='1')


    class Meta:
        model = ConnectionOnDevice
        fields = ["port", "connected", "vlan", "ip_client", "comment"]

intranet/intranet/connection_on_device/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.contrib import messages
from django import forms
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.mail import send_mail

import re

from connection_on_device.models import ConnectionOnDevice
from models_device.models import Device
from connection_on_device.forms import AddConnectionForm

# Create your views here.

COLORS = {"Switch":'Lime', "RWR":'Yellow', "UBNT":'Gold'}


def index(request):
    all_dev = Device.objects.all()

    return render(request, "dev_list_con.html", {
        "devices":all_dev, 
        })


def on_device_get(request, id_dev):

    try:
        dev = Device.objects.get(pk=id_dev)
    except Device.DoesNotExist:
        raise Http404('Device not found!')

    all_connection = ConnectionOnDevice.objects.filter(id_dev=dev)

    connections = []

    for connection in all_connection:
        vlan = f'/{connection.vlan}vlan'

        if connection.connected == 'UP':
            try:
                up_dev = Device.objects.get(ip=dev.up_connect_ip)
                connection.connected = (f'UP to {dev.up_connect_port} port on {dev.model.type} {dev.up_connect_ip}', up_dev)
            except Device.DoesNotExist:
                connection.connected = f'UP to {dev.up_connect_port} port on {dev.model.type} {dev.up_connect_ip}'
        elif 'DOWN to ' in connection.connected:
            try:
                down_dev = Device.objects.get(ip=connection.connected[8:])
                connection.connected = (connection.connected, down_dev)
            except Device.DoesNotExist:
                connection.connected = connection.connected
 
        if connection.vlan != "Null":
            connection.vlan = vlan
        else:
            connection.vlan = ""

        connections.append(connection)
    connections = sorted(connections, key=lambda x: x.port)
    
    return connections, dev


def on_device(request, id_dev):
    connections, dev = on_device_get(request, id_dev)
    
    return render(request, "connection.html", {
        "connections":connections, 
        "dev":dev,
        "color":COLORS[dev.model.type],
        })


def path_to(request, id_dev):

    try:
        dev = Device.objects.get(pk=id_dev)
    except Device.DoesNotExist:
        raise Http404('Device not found!')

    path = [(dev, COLORS[dev.model.type])]
    to_dev = dev

    if dev.up_connect_ip == '255.255.255.255':
        return render(request, "path_to_device.html", {
                "path": path,
                "to_dev": to_dev,
                })

    if_loop = 0
    while True:
        if_loop += 1
        try:
            dev = Device.objects.get(ip=dev.up_connect_ip)
        except Device.DoesNotExist:
            raise Http404('Device not found!')
        

        if str(dev.up_connect_ip) == '255.255.255.255':
            path.append((dev, COLORS[dev.model.type]))
            return render(request, "path_to_device.html", {
                "path": path,
                "to_dev": to_dev,
                })
        else:
            path.append((dev, COLORS[dev.model.type]))

        if if_loop > 15:
            return HttpResponse('path not found')


def serch_connect(connect_on_port):
    # check for a downstream connection in the port, if it has - return object device
    ip_pattern = '\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}'
    _search = re.search(ip_pattern, connect_on_port)
    if _search is not None:
        result = Device.objects.get(ip=_search.group())
    else:
        result = False
    return result


def all_connection_port(dev, connections_dev):
    # get all connection on one device
    all_connection = ConnectionOnDevice.objects.filter(id_dev=dev)
    connections = []
    list_connection_lower_dev = []

    for connection in all_connection:
        _search = serch_connect(connection.connected)
        if _search:
            list_connection_lower_dev.append(_search)
        vlan = f'/{connection.vlan}vlan'

        if connection.connected == 'UP':
            connection.connected = f'UP to {dev.up_connect_port} port on {dev.model.type} {dev.up_connect_ip}'

        if connection.vlan != "Null":
            connection.vlan = vlan
        else:
            connection.vlan = ""
        connections.append(connection)
    connections_dev.append((dev, COLORS[dev.model.type], sorted(connections, key=lambda x: x.port)))

    for _dev in list_connection_lower_dev:
        all_connection_port(_dev, connections_dev)

    return connections_dev


def all_connection(request, id_dev):
    # get all connection on all devices from the needed device
    connections_dev = []
    try:
        dev = Device.objects.get(pk=id_dev)
    except Device.DoesNotExist:
        raise Http404('Device not found!')

    source_connect = dev
    connections = all_connection_port(dev, connections_dev) 
    
    
    return render(request, "all_connection_from.html", {
        "connections":connections, 
        "source":source_connect
        })


class AddConnection(PermissionRequiredMixin, TemplateView):
    form = None
    template_name = "add_connection.html"
    permission_required = ('connection_on_device.add_connectionondevice', )

    def get(self, request, *args, **kwargs):
        self.form = AddConnectionForm()
        self.connections, self.dev = on_device_get(request, self.kwargs['id_dev'])

        return super(AddConnection, self).get(request, *args, **kwargs)


    def get_context_data(self, *args, **kwargs):
        context = super(AddConnection, self).get_context_data(*args, **kwargs)
        context['form'] = self.form
        context['dev'] = self.dev
        context['connections'] = self.connections
        context['color'] = COLORS[self.dev.model.type]

        return context


    def post(self, request, *args, **kwargs):
        id_dev = self.kwargs['id_dev']
        dev = Device.objects.get(pk=id_dev)
        self.form = AddConnectionForm(request.POST)

        if self.form.is_valid():
            connection = ConnectionOnDevice()
            connection.id_dev = dev
            connection.port = self.form.cleaned_data['port']
            connection.connected = self.form.cleaned_data['connected']
            connection.vlan = self.form.cleaned_data['vlan']
            connection.ip_client = self.form.cleaned_data['ip_client']
            connection.comment = self.form.cleaned_data['comment']
            connection.save()
            messages.add_message(request, messages.SUCCESS, "<b>Подключение добавлено.</b>")
            return redirect('connections_on_dev', id_dev=id_dev)
        else:
            return super(AddConnection, self).get(request, *args, **kwargs)


class DelConnection(PermissionRequiredMixin, TemplateView):
    form = None
    permission_required = ('connection_on_device.delete_connectionondevice', )


    def post(self, request, *args, **kwargs):
        id_dev = self.kwargs['id_dev']
        id_connection = request.POST['connection_to_delete']
        self._to_del = ConnectionOnDevice.objects.get(pk=id_connection)
        self._to_del.delete()
        messages.add_message(request, messages.SUCCESS, f"<b>Подключение удалено.<br>{self._to_del}</b>")
        # mail_message = f"""Удалено подключение:
        #     {self._to_del}
        #     """
        # send_mail(
        #     'Изменения в интранете.',
        #     mail_message,
        #     'vvvvvv@mail.ru',
        #     ['vvvvvv@mail.ru'],
        #     fail_silently=False,
        # )

        return redirect('connections_on_dev', id_dev)


class EditConnection(PermissionRequiredMixin, TemplateView):
    form = None
    template_name = 'edit_connection.html'
    permission_required = ('connection_on_device.change_connectionondevice', )

    def get(self, request, *args, **kwargs):
        self.id_con = self.kwargs['id_con']
        self.connection_instance = ConnectionOnDevice.objects.get(pk=self.id_con)
        self.form = AddConnectionForm(instance=self.connection_instance)
        self.connections, self.dev = on_device_get(request, self.kwargs['id_dev'])

        return super(EditConnection, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(EditConnection, self).get_context_data(*args, **kwargs)
        context['form'] = self.form
        context['dev'] = self.dev
        context['connections'] = self.connections
        context['id_con'] = self.id_con
        context['color'] = COLORS[self.dev.model.type]

        return context

    def post(self, request, *args, **kwargs):
        self.form = AddConnectionForm(request.POST)
        if self.form.is_valid():
            old_connection = ConnectionOnDevice.objects.get(pk=self.kwargs['id_con'])
            connection = ConnectionOnDevice.objects.get(pk=self.kwargs['id_con'])

            connection.id_dev = Device.objects.get(pk=self.kwargs['id_dev'])
            connection.port = self.form.cleaned_data['port']
            connection.connected = self.form.cleaned_data['connected']
            connection.vlan = self.form.cleaned_data['vlan']
            connection.ip_client = self.form.cleaned_data['ip_client']
            connection.comment = self.form.cleaned_data['comment']
            connection.save()
            messages.add_message(request, messages.SUCCESS, "Изменения приняты.")

            mail_message = f"""Изменения приняты:
            устройство({'без изменений' if old_connection.id_dev == connection.id_dev else '--- изменено ---'}): {connection.id_dev.ip} 
            порт({'без изменений' if old_connection.port == connection.port else '--- изменено ---'}): {connection.port} 
            подключение({'без изменений' if old_connection.connected == connection.connected else '--- изменено ---'}): {connection.connected} 

intranet/intranet/connection_on_device/templates/add_connection.html
{% extends "base.html" %}
{% load static %}

{% block title %}Подключения{% endblock %}
{% block head %} 
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Список устройств</a></li>
		    <li class="breadcrumb-item"><a href="{% url 'all_connection' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать все подключения от этого узла">
									    	Показать все подключения от {{ dev.ip }}
										</a>
			</li>
		  </ol>
		</nav>
{% endblock %}
 
{% block main %}
		<table class="table table-sm table-hover w-75">
			<tr>
				<td bgcolor="{{ color }}">
					{{ dev.model.type }}&nbsp;{{ dev.model.model }}
				</td>
				<td>
					сети&nbsp;
				</td>				
				<td bgcolor="{{ color }}">
					<a href="{% url 'path_to_dev' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать путь до данного узла">{{ dev.ip }}</a>
				</td>
				<td>
					комментарий
				</td>
			</tr>
			{% for connection in connections %}
			<tr>
				<td>
					{% if 'UP to' in connection.connected.0 or 'DOWN to' in connection.connected.0 %}
						<a href="{% url 'connections_on_dev' connection.connected.1.pk %}" data-toggle="tooltip" data-placement="top" 
						title="Показать подключения на данном устройстве">{{ connection.connected.0 }}</a>
					{% else %}
						{{ connection.connected }}
					{% endif %}
				</td>
				<td>
					{{ connection.ip_client }}
				</td>
				<td>
					{% include 'port_block.html' %}
				</td>
				<td>
					{% include "comment_block.html" %}
				</td>
			</tr>
			{% endfor %}
				<form action="" method="post">
					{% csrf_token %}
					<tr>
						<td>
							<small class="form-text text-muted">{{ form.connected.help_text }}</small>
							{{ form.connected }}
						</td>
						<td>
							<small class="form-text text-muted">{{ form.ip_client.help_text }}</small>
							{{ form.ip_client }}
						</td>
						<td>
							{% include "port_form_radio.html" %}
							<small class="form-text text-muted">{{ form.vlan.help_text }}</small>
							{{ form.vlan }}
						</td>
						<td>
							<small class="form-text text-muted">{{ form.comment.help_text }}</small>
							{{ form.comment }}
						</td>
					</tr>
					<tr>
						<td colspan="3">
							<input class="btn btn-outline-secondary" type="submit" name="add_device" value="Добавить">
							<a href="{% url 'connections_on_dev' dev.pk %}" class="btn btn-outline-secondary">Назад</span></a>
						</td>
					</tr>
				</form>
		</table>
{% endblock %}

intranet/intranet/connection_on_device/templates/all_connection_from.html
{% extends "base.html" %}

{% block title %}Подключения{% endblock %}
{% block head %}
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Список устройств</a></li>
		  	<li class="breadcrumb-item"><a href="{% url 'connections_on_dev' source.pk %}">Вернуться к подключению только на {{ source.ip }} </a></li>
		    <li class="breadcrumb-item">Все подключения от {{ source.ip }} {{ source.comment }} </li>
		  </ol>
		</nav>
{% endblock %}

{% block main %}
		<table class="table table-sm table-hover w-75">
		{% for dev, color, connect in connections %}
			<thead>
				{% if forloop.first %}
					<tr>
						<td colspan="4">
							<b>Подключения в {{ dev.city.get_region_display}} ОП {{ dev.city.city }}</b>
					</td>
					</tr>
				{% endif %}
			<tr>
				<th bgcolor="{{ color }}">
					{{ dev.model.type }}&nbsp;{{ dev.model.model }}
				</th>
				<th>
					сети&nbsp;
				</th>				
				<th bgcolor="{{ color }}">
					<a style="text-decoration:none;" href="{% url 'path_to_dev' dev.pk %}">{{ dev.ip }}</a>
				</th>
				<th>
					комментарий&nbsp;
				</th>	
			</tr>
		</thead>
			{% for connection in connect %}
			<tr>
				<td>
					{{ connection.connected }}
				</td>
				<td>
					{{ connection.ip_client }}
				</td>
				<td>
					{{ connection.port }}port{{ connection.vlan }}
				</td>
				<td>
					{% include "comment_block.html" %}
				</td>
			</tr>
			{% endfor %}
		
		{% endfor %}
		</table>
{% endblock %}

intranet/intranet/connection_on_device/templates/comment_block.html
					{% if connection.comment|length > 35 %}
						<div id="block_comment">
							{{ connection.comment }}
						</div>
					{% else %}
						{{ connection.comment }}
					{% endif %}

intranet/intranet/connection_on_device/templates/connection.html
{% extends "base.html" %} 
{% load static %}

{% block title %}Подключения{% endblock %}
{% block head %} 
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Список устройств</a></li>
		    <li class="breadcrumb-item">
		    	<a href="{% url 'all_connection' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать все подключения от этого узла">
			    	Показать все подключения от {{ dev.ip }}
				</a>
			</li>
		  </ol>
		</nav>
{% endblock %}
 
{% block main %}
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == "success" %} <div class="alert-success mb-2 w-50">
				{% elif message.tags == "error" %} <div class="alert-danger mb-2 w-50">
				{% else %} <div class="alert-secondary mb-2 w-50">{% endif %}
					{% autoescape off %} {{ message }} {% endautoescape %}
				</div>
			{% endfor %}
		{% endif %}
		<table class="table table-sm p-0 table-hover w-75">
			<tr>
				<td colspan="4">
					Подключение в {{ dev.city.get_region_display}} ОП {{ dev.city.city }}
				</td>
			</tr>
			<tr>
				<td bgcolor="{{ color }}" colspan="2">
					{{ dev.model.type }}&nbsp;{{ dev.model.model }}
				</td>
				<td>
					сети&nbsp;
				</td>				
				<td bgcolor="{{ color }}">
					<a href="{% url 'path_to_dev' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать путь до данного узла">{{ dev.ip }}</a> {{ dev.comment }}
				</td>
				<td colspan="2">
					комментарий
				</td>
			</tr>
			{% for connection in connections %}
			<tr>
				<td>
					{% if perms.connection_on_device.change_connectionondevice %}
						{% if 'UP to' in connection.connected.0 or 'DOWN to' in connection.connected.0 %}
						{%else%}
							{% if 'UP to' in connection.connected %}
							{%else%}
		          			<a class="alert-link text-dark" 
		          			href="{% url 'edit_connection' dev.pk connection.pk %}" data-toggle="tooltip" data-placement="left" title="Редактировать подключение">
								<img src="{% static "img/edit.png" %}" width="20" height="20">
							</a>
							{% endif %}
						{% endif %}
					{% endif %}
				</td>
				<td>
					{% if 'UP to' in connection.connected.0 or 'DOWN to' in connection.connected.0 %}
						<a href="{% url 'connections_on_dev' connection.connected.1.pk %}" data-toggle="tooltip" data-placement="top" 
						title="Показать подключения на данном устройстве">{{ connection.connected.0 }}</a>
					{% else %}

						{{ connection.connected }}
					{% endif %}
				</td>
				<td>
					{{ connection.ip_client }}
				</td>
				<td>
					{% include 'port_block.html' %}
				</td>
				<td>
					{% include "comment_block.html" %}
				</td>
				<td>
					{% if perms.connection_on_device.delete_connectionondevice %}
						{% if 'UP to' in connection.connected.0 or 'DOWN to' in connection.connected.0 %}
							{%else%}
							<a href="" data-toggle="modal" data-target="#deleteModal{{ connection.pk }}" >
								<img src="{% static "img/delete.png" %}" width="20" height="20"title="Удалить подключение">
							</a>

							<!-- Modal -->
							<div class="modal fade" id="deleteModal{{ connection.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteModal{{ connection.pk }}" aria-hidden="true">
							  <div class="modal-dialog modal-dialog-centered" role="document">
							    <div class="modal-content">
							      <div class="modal-header">
							        <h5 class="modal-title" id="deleteModal{{ connection.pk }}">Удаление подключения!!!</h5>
							        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
							          <span aria-hidden="true">&times;</span>
							        </button>
							      </div>
							      <div class="modal-body">
							        Удалить подключение:<br>
							        <b>{{ connection.connected }}
							        	{% if connection.ip_client > 0 %}
							        		({{ connection.ip_client }})&nbsp;
							        	{% endif %}
							    		{{ connection.port }}port
										{{ connection.vlan }}
									</b>
							      </div>
							      <div class="modal-footer">
							        <form action="{% url 'del_connection' dev.pk %}" method="post">
										<div class="form-group">
											<button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
											{% csrf_token %}
											<input type="hidden" name="connection_to_delete" value="{{ connection.pk }}">
											<input class="btn btn-outline-danger" type="submit" name="del_connection" value="Удалить">
										</div>
									</form>
							      </div>
							    </div>
							  </div>
							</div>
						{% endif %}
					{% endif %}
				</td>
			</tr>
			{% endfor %}
			<tr>
				<td colspan="5">
					{% if perms.connection_on_device.add_connectionondevice %}
					<a class="alert-link text-dark" href="{% url 'add_connection' dev.pk %}" data-toggle="tooltip" data-placement="top" title="добавить подключение">
						<img src="{% static "img/add.png" %}" width="32" height="32">
					</a>
					{% endif %}
				</td>
			</tr>
		</table>
{% endblock %}

intranet/intranet/connection_on_device/templates/edit_connection.html
{% extends "base.html" %}
{% load static %}

{% block title %}Подключения{% endblock %}
{% block head %} 
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Список устройств</a></li>
		    <li class="breadcrumb-item">
		    	<a href="{% url 'all_connection' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать все подключения от этого узла">
					Показать все подключения от {{ dev.ip }}
				</a>
			</li>
		  </ol>
		</nav>
{% endblock %}
 
{% block main %}
		<table class="table table-sm w-75">
			<thead>
				<tr>
					<th scope="col" bgcolor="{{ color }}">
						{{ dev.model.type }}&nbsp;{{ dev.model.model }}
					</th>
					<th scope="col">
						сети&nbsp;
					</th>				
					<th scope="col" bgcolor="{{ color }}">
						<a href="{% url 'path_to_dev' dev.pk %}" data-toggle="tooltip" data-placement="right" title="Показать путь до данного узла">{{ dev.ip }}</a>
					</th>
					<th scope="col" >
						комментарий
					</th>	
				</tr>
			</thead>
			{% for connection in connections %}
				{% if connection.pk == id_con %}
					<form action="" method="post">
					{% csrf_token %}
						<tr>
							<td>
								<small class="form-text text-muted">{{ form.connected.help_text }}</small>
								{{ form.connected }}
							</td>
							<td>
								<small class="form-text text-muted">{{ form.ip_client.help_text }}</small>
								{{ form.ip_client }}
							</td>
							<td>
								{% include "port_form_radio.html" %}
								<small class="form-text text-muted">{{ form.vlan.help_text }}</small>
								{{ form.vlan }}
							</td>
							<td>
								<small class="form-text text-muted">{{ form.comment.help_text }}</small>
								{{ form.comment }}
							</td>
						</tr>
					{% else %}
						<tr>
							<td>
								{% if 'UP to' in connection.connected.0 or 'DOWN to' in connection.connected.0 %}
									<a href="{% url 'connections_on_dev' connection.connected.1.pk %}" data-toggle="tooltip" data-placement="top" 
									title="Показать подключения на данном устройстве">{{ connection.connected.0 }}</a>
								{% else %}
									{{ connection.connected }}
								{% endif %}
							</td>
							<td>
								{{ connection.ip_client }}
							</td>
							<td>
								{% include 'port_block.html' %}
							</td>
							<td>
								{% include "comment_block.html" %}
							</td>
						</tr>
					{% endif %}
			{% endfor %}
						<tr>
							<td colspan="4">
								<input class="btn btn-outline-secondary" type="submit" name="add_device" value="Сохранить">
								<a href="{% url 'connections_on_dev' dev.pk %}" class="btn btn-outline-secondary">Отменить</span></a>
							</td>
						</tr>
					</form>
		</table>
{% endblock %}

intranet/intranet/connection_on_device/templates/path_to_device.html
{% extends "base.html" %}

{% block title %}Подключения{% endblock %}
{% block head %} Путь до {{ to_dev.ip }} {% endblock %}
{% block main %}
		<table class="table table-hover w-50">

			<tr><td align="center">
				{% for dev, color in path %}
					
						<a style="background: {{ color }}" href="{% url 'connections_on_dev' dev.pk %}" title="Показать подключения на данном устройстве">{{ dev.ip }}</a>
						{% if forloop.last %}
							:{{ dev.incoming_port }} <font size="4" color="red"><b>&#8596;</b></font> CISCO
						{% else %}
							:{{ dev.incoming_port }}<font size="4" color="red"><b>&#8596;</b></font> {{ dev.up_connect_port }}:
						{% endif %}
					
				{% endfor %}
			</tr></td>
		</table>
{% endblock %}

intranet/intranet/connection_on_device/templates/port_block.html
					{% if 'RWR' in dev.model.type %}
						{{ connection.port }} {{ connection.vlan }}
					{% else %}
						{{ connection.port }}port{{ connection.vlan }}
					{% endif %}

intranet/intranet/connection_on_device/templates/port_form_radio.html
							{% if 'RWR' in dev.model.type %}
							<small class="form-text text-muted">{{ form.port.help_text }}</small>
							<select id="getPort" onchange="ifRadioCheck(this);">
								<option value="eth0">eth0</option>
								<option value="eth1">eth1</option>
							</select>
							<script type="text/javascript">
								function ifRadioCheck(nameSelect)
									{
									    console.log(nameSelect);
									    if(nameSelect){
									        $('#id_port').val(nameSelect.value)
									    }
									}
							</script>
							{{ form.port.as_hidden }}
							
							{% else %}
							<small class="form-text text-muted">{{ form.port.help_text }}</small>
							{{ form.port }}
							{% endif %}