intranet/intranet/intranet/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from models_device.views import DeviceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(),
    {'template_name': "login.html",
    'extra_context': {}}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', DeviceView.as_view(), name='device'),
    path('device/', include('models_device.urls')),
    path('connection/', include('connection_on_device.urls')),
]

intranet/intranet/models_device/models.py
from django.db import models
from django.core.exceptions import ValidationError

# My 
from cities.models import Cities, REGIONS

# Create your models here.

def validate_up_connect_ip(ip):
    if ip != '255.255.255.255':
        try:
            id_dev = Device.objects.get(ip=ip)
        except Device.DoesNotExist:
            raise ValidationError("Указанного вышестоящего оборудования не существует.")


class ModelDevices(models.Model):
    type = models.CharField(max_length=30, verbose_name='Тип устройства')
    model = models.CharField(max_length=30, help_text='модель устройства', verbose_name='Модель')
    ports = models.PositiveSmallIntegerField(help_text='количество портов', verbose_name='Портов')
    template = models.CharField(max_length=50,help_text='имя файла с шаблоном', verbose_name='Шаблон')
    comment = models.TextField(blank=True, verbose_name='Комментарий', help_text='комментарий')

    class Meta:
        verbose_name = 'Тип и модель оборудования'
        verbose_name_plural = 'Типы и модели оборудования'
        ordering = ['model']

    def __str__(self):
        _text = f"{self.type} {self.model} {self.comment}"

        return _text


class Device(models.Model):
    model = models.ForeignKey(ModelDevices, null=True, on_delete=models.SET_NULL, help_text='модель устройства', verbose_name='Модель')
    ip = models.GenericIPAddressField(unique=True, help_text='IP нового устройства', verbose_name='IP устройства')
    incoming_port = models.CharField(max_length=10, help_text='приходящий порт', default=1, verbose_name='Приходящий порт')
    up_connect_ip = models.GenericIPAddressField(validators=[validate_up_connect_ip], help_text='IP устройства от которого подключено', verbose_name='IP вышестоящего')
    up_connect_port = models.CharField(max_length=10, help_text='порт подключения на вышестоящем устройстве', default=1, verbose_name='Порт вышестоящего')
    city = models.ForeignKey(Cities, on_delete=models.PROTECT, help_text='город подключения', verbose_name='Город')
    comment = models.TextField(blank=True, verbose_name='Комментарий', help_text='комментарий')
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        _text = f"{REGIONS[self.city.region-1][1]} {self.city.city} {self.ip} ({self.model.model}) connect from: {self.up_connect_ip}; Comment: {self.comment}; "
        return _text

    class Meta:
        verbose_name = 'Установленное оборудование'
        verbose_name_plural = 'Установленное оборудование'

intranet/intranet/templates/base.html
{% load static %}
<!DOCTYPE html>
 
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="stylesheet"  type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet"  type="text/css" href="{% static "css/intranet.css" %}">
    <link rel="shortcut icon" type="image/png" href="{% static "/favicon.ico" %}">

  </head>
  <body class="bg-light">

    <header>
      <div class="container bg-secondary mw-100 p-2">
        <div class="row">
          <div class="col">
            {% if region %}
              {% if city %}
                <form action="{% url 'dev_list_city' region city %}">
              {% else %}
                <form action="{% url 'dev_list_region' region %}">
              {% endif %}  
            {% else %}
            <form action="{% url 'dev_list' %}">
            {% endif %}  
            <div class="form-group form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Поиск" aria-label="Search" name="search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
            </div>
            <div class="form-group  my-sm-0">
              <div class="form-check">
                <input class="form-check-input" type="checkbox" id="gridCheck" name="only_dev">
                <label class="form-check-label" for="gridCheck">Искать только устройство</label>
              </div>
            </div>
  
            </form>
          </div>
          <div class="col" align="right">
             {% if user.is_authenticated %}
              <table>
                <tr><td class="text-white"><b>{{ user }}</b></td></tr>
                <tr><td><a class="text-light" href="{% url 'logout' %}">Выйти</a></td></tr>
              </table>
             {% else %}
              <a class="text-light" href="{% url 'login' %}">Войти</a>
             {% endif %}
          </div>
        </div>
      </div>
    </header>

    <main role="main">
      <div class="container mw-100 p-2">
        <div class="row">
          <div class="col">
            <table>
              {% if perms.models_device.add_device %}
              <tr>
                <td>
                  {% if region %}
                  {# Если регион выбран, выводим его название #}
                      
                  {# Если город выбран, выводим его название #}
                      {% if city %}
                        <a class="alert-link text-dark" href="{% url 'device_add_city' region city %}">Добавить устройство</a>
                      {% else %}
                        <a class="alert-link text-dark" href="{% url 'device_add_reg' region %}">Добавить устройство</a>
                      {% endif %}

                  {# Если регион не выбран #}
                  {% else %}
                      <a class="alert-link text-dark" href="{% url 'device_add' %}">Добавить устройство</a>
                  {% endif %}
                </td>
              </tr>
              {% endif %}
                          
              <tr>
                <td>
                  <a class="alert-link text-dark" href="{% url 'device' %}">Список всех устройств</a>
                </td>
              </tr>
<!--               <tr>
                <td>
                  <a class="alert-link text-dark" href="#">Поиск устройства</a>
                </td>
              </tr>
              <tr>
                <td>
                  <a class="alert-link text-dark" href="#">Поиск клиента</a>
                </td>
              </tr> -->
            </table>
            
          </div>
          <div class="col-10">

                <div class="row">
                  <div class="col">
                    <small>
                    {% block head %}
                    {% endblock %}
                    </small>
                  </div>
                </div>
                <div class="row">
                  <div class="col">
                    <small>
                    {% block main %}
                    {% endblock %}
                    </small>
                  </div>
                </div>

          </div>
        </div>
      </div>
    </main>
  <script src="{% static "js/jquery.js" %}"></script>
  <script src="{% static "js/popper.min.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script>
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      })
    </script>
  </body>
</html>

intranet/intranet/templates/error.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список устройств{% endblock %}
{% block main %}
Error
{% endblock %}