intranet/intranet/intranet/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from models_device.views import DeviceView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(),
    {'template_name': "login.html",
    'extra_context': {}}, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', DeviceView.as_view(), name='device'),
    path('device/', include('models_device.urls')),
    path('connection/', include('connection_on_device.urls')),
]

intranet/intranet/models_device/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from models_device import views
from models_device.views import DeviceView, DeviceCreate, DeviceUpdate, DeviceDelete

urlpatterns = [
	path('', DeviceView.as_view(), name='device'),
	path('add', login_required(DeviceCreate.as_view()), name='device_add'),
	path('<str:region>/add', login_required(DeviceCreate.as_view()), name='device_add_reg'),
	path('<str:region>/<str:city>/add', login_required(DeviceCreate.as_view()), name='device_add_city'),
	path('delete', login_required(DeviceDelete.as_view()), name='device_delete'),
	path('edit/<int:dev_id>', login_required(DeviceUpdate.as_view()), name='device_edit'),
	path('<str:region>/edit/<int:dev_id>', login_required(DeviceUpdate.as_view()), name='device_edit_reg'),
	path('<str:region>/<str:city>/edit/<int:dev_id>', login_required(DeviceUpdate.as_view()), name='device_edit_city'),
	path('<str:region>/', DeviceView.as_view(), name='dev_list_region'),
	path('<str:region>/<str:city>/', DeviceView.as_view(), name='dev_list_city'),
]

intranet/intranet/models_device/models.py
from django.db import models
from django.core.exceptions import ValidationError

# My 
from cities.models import Cities, REGIONS

# Create your models here.

def validate_up_connect_ip(ip):
    if ip != '255.255.255.255':
        try:
            id_dev = Device.objects.get(ip=ip)
        except Device.DoesNotExist:
            raise ValidationError("Указанного вышестоящего оборудования не существует.")


class ModelDevices(models.Model):
    type = models.CharField(max_length=30, verbose_name='Тип устройства')
    model = models.CharField(max_length=30, help_text='модель устройства', verbose_name='Модель')
    ports = models.PositiveSmallIntegerField(help_text='количество портов', verbose_name='Портов')
    template = models.CharField(max_length=50,help_text='имя файла с шаблоном', verbose_name='Шаблон')
    comment = models.TextField(blank=True, verbose_name='Комментарий', help_text='комментарий')

    class Meta:
        verbose_name = 'Тип и модель оборудования'
        verbose_name_plural = 'Типы и модели оборудования'
        ordering = ['model']

    def __str__(self):
        _text = f"{self.type} {self.model} {self.comment}"

        return _text


class Device(models.Model):
    model = models.ForeignKey(ModelDevices, null=True, on_delete=models.SET_NULL, help_text='модель устройства', verbose_name='Модель')
    ip = models.GenericIPAddressField(unique=True, help_text='IP нового устройства', verbose_name='IP устройства')
    incoming_port = models.CharField(max_length=10, help_text='приходящий порт', default=1, verbose_name='Приходящий порт')
    up_connect_ip = models.GenericIPAddressField(validators=[validate_up_connect_ip], help_text='IP устройства от которого подключено', verbose_name='IP вышестоящего')
    up_connect_port = models.CharField(max_length=10, help_text='порт подключения на вышестоящем устройстве', default=1, verbose_name='Порт вышестоящего')
    city = models.ForeignKey(Cities, on_delete=models.PROTECT, help_text='город подключения', verbose_name='Город')
    comment = models.TextField(blank=True, verbose_name='Комментарий', help_text='комментарий')
    update = models.DateTimeField(auto_now=True)

    def __str__(self):
        _text = f"{REGIONS[self.city.region-1][1]} {self.city.city} {self.ip} ({self.model.model}) connect from: {self.up_connect_ip}; Comment: {self.comment}; "
        return _text

    class Meta:
        verbose_name = 'Установленное оборудование'
        verbose_name_plural = 'Установленное оборудование'

intranet/intranet/models_device/forms.py
from django import forms

from models_device.models import Device

class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ['model', 'ip', 'incoming_port', 'up_connect_ip', 'up_connect_port', 'city', 'comment']
        error_messages = {'ip': {'unique': 'Устройство с таким IP уже существует.'}
        }


class DeviceDeleteForm(forms.Form):
    device_to_delete = forms.IntegerField() 

intranet/intranet/models_device/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.core.paginator import InvalidPage
from django.views.generic.list import ListView
from django.views.generic.base import ContextMixin
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin


from models_device.models import Device
from cities.models import Cities
from connection_on_device.models import ConnectionOnDevice
from models_device.forms import DeviceForm, DeviceDeleteForm

# Create your views here.

class PathToCityMixin(ContextMixin):
    def __init__(self, *args, **kwargs):
        super(PathToCityMixin, self).__init__(*args, **kwargs)
        
        self.regions = Cities.all_regions()


    def search(self, reg=False, cit=False):
        result = []
        result_search = []
        search_query = self.request.GET.get('search', '').strip()
        only_dev = self.request.GET.get('only_dev', '').strip()
        city_obj = cit

        if only_dev:  # если ищем только девайс, то нужен поиск только в else
            reg=False
            cit=False

        if cit:
            for dev in list(Device.objects.filter(city=city_obj)):
                result_search += list(ConnectionOnDevice.objects.filter(id_dev=dev).filter(connected__icontains=search_query))
            for i in result_search:
                result.append(i.id_dev)
            return [result, result_search]
        elif reg:
            for _city in self.reg:
                for dev in list(Device.objects.filter(city=_city)):
                    result_search += list(ConnectionOnDevice.objects.filter(id_dev=dev).filter(connected__icontains=search_query))
            for i in result_search:
                result.append(i.id_dev)
            return [result, result_search]

        else:
            if only_dev:  # если ищем только устройство
                result_search = Device.objects.filter(ip=search_query)
            else:
                result_search = ConnectionOnDevice.objects.filter(connected__icontains=search_query)

            for i in result_search:
                if only_dev:  # если ищем только устройство, добавляем его в результат
                    result.append(i)
                else:  # если ищем в подключениях - добавляем устройства, с которых подключено
                    result.append(i.id_dev)

            return (result, result_search)


    def _city(self):
        search_query = self.request.GET.get('search', '').strip()

        try:
            city_obj = Cities.objects.filter(city=self.kwargs["city"]).first()
        except Cities.DoesNotExist:
            raise Http404('Device not found!') 

        if search_query:
            result, result_search = self.search(cit=city_obj)
            return [result, result_search]  
        else:
            return [Device.objects.filter(city=city_obj)]


    def _region(self):
        all_dev = []
        search_query = self.request.GET.get('search', '').strip()
        
        if search_query:
            result, result_search = self.search(reg=True)
            return [result, result_search]  
        else:
            for _city in self.reg:
                all_dev += list(Device.objects.filter(city=_city))
            return [all_dev]


    def _all_dev(self):
        search_query = self.request.GET.get('search', '').strip()
        
        if search_query:  # если задана строка поиска
            result, result_search = self.search()
            return [result, result_search]  
        else:
            return [Device.objects.all().order_by('city')]    


    def get(self, request, *args, **kwargs):
        current_user = request.user
        if "city" in self.kwargs:
            self._action_list = [self._city, "city", "region", "regions", "cities"]
            self.kwargs["regions"] = self.regions
            if Cities.get_reg_id(self.kwargs["region"]): # if there is such region
                reg_id = Cities.get_reg_id(self.kwargs["region"])
                try:
                    self.reg = Cities.objects.filter(region=reg_id)
                except Cities.DoesNotExist:
                    raise Http404('Device not found!') 
                self.kwargs["cities"] = self.reg
            try:
                Cities.objects.get(city=self.kwargs["city"])
            except Cities.DoesNotExist: # if there is no such city
                return redirect('device')
        elif "region" in self.kwargs:
            self._action_list = [self._region, "cities", "region", "regions"]
            if Cities.get_reg_id(self.kwargs["region"]): # if there is such region
                reg_id = Cities.get_reg_id(self.kwargs["region"])
                try:
                    self.reg = Cities.objects.filter(region=reg_id)
                except Cities.DoesNotExist:
                    raise Http404('Device not found!') 
                self.kwargs["cities"] = self.reg
                self.kwargs["regions"] = self.regions
            else:
                return redirect('device')
        else:
            self._action_list = [self._all_dev, "regions"]
            self.kwargs["regions"] = self.regions
            
        return super(PathToCityMixin, self).get(request, *args, **kwargs)


    def get_context_data(self, **kwargs):
        self.context = super(PathToCityMixin, self).get_context_data(**kwargs)

        for _key in self._action_list[1:]:
            self.context[_key] = self.kwargs[_key]
            # forming string view 'Region2 (Orel, Kursk, Voronezh)'
            #
            # if _key == "regions":
            #     cities = []
            #     for region in self.regions:
            #         _refion_with_sity_string = ""
            #         _citys_in_region = Cities.objects.filter(region=Cities.get_reg_id(region))
            #         _city_text = []
            #         for city_obj in _citys_in_region:
            #             _city_text.append(city_obj.city)
            #         _refion_with_sity_string += f" ( {', '.join(_city_text)} )"
            #         cities.append(_refion_with_sity_string)
            #     self.context["regions"] = zip(self.regions, cities)
                # end forming

        return self.context




class DeviceView(PathToCityMixin, ListView):
    template_name = "dev_list.html"
    paginate_by = 12


    def get_queryset(self):
        return self._action_list[0]()  # from PathToCityMixin


class DeviceCreate(PathToCityMixin, TemplateView):
    form = None
    template_name = "device_add.html"


    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.has_perm("models_device.add_device"):
                if "city" in self.kwargs:  # Если город определен, то выводим его в форме по умолчанию
                    self.form = DeviceForm(initial={'city': Cities.objects.filter(city=self.kwargs["city"]).first()})
                    print(self.kwargs["city"])
                else:
                    self.form = DeviceForm()

                return super(DeviceCreate, self).get(request, *args, **kwargs)
            else:
                return redirect("/login/?next=", request.path)
        else:
            return redirect("/login/?next=", request.path)    

    def get_context_data(self, **kwargs):
        context = super(DeviceCreate, self).get_context_data(**kwargs)
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):
        self.form = DeviceForm(request.POST)

        if self.form.is_valid():
            # Сохранение нового устройства
            self.form.save()

            # Добавление нового устройства на подключение к порту вышестоящего
            connect_on_dev = self.form.cleaned_data['up_connect_ip']
            if connect_on_dev != '255.255.255.255':
                form_connection_to_up = ConnectionOnDevice()
                form_connection_to_up.id_dev = Device.objects.get(ip=connect_on_dev)
                form_connection_to_up.port = self.form.cleaned_data['up_connect_port']
                form_connection_to_up.connected = f"DOWN to {self.form.cleaned_data['ip']}"
                form_connection_to_up.save()
                messages.add_message(request, messages.SUCCESS, 
                    f"На вышестоящем {connect_on_dev} добавлено: <b>DOWN to {self.form.cleaned_data['ip']} port {self.form.cleaned_data['up_connect_port']}</b>")
          


            # Добавление UP порта на новое устройство
            form_connection_to_me = ConnectionOnDevice()
            form_connection_to_me.id_dev = Device.objects.get(ip=self.form.cleaned_data['ip'])
            form_connection_to_me.port = self.form.cleaned_data['incoming_port']
            form_connection_to_me.connected = "UP"
            form_connection_to_me.save()
            messages.add_message(request, messages.SUCCESS, 
                    f"На новом {self.form.cleaned_data['ip']} добавлено: <b>UP to {self.form.cleaned_data['up_connect_ip']} port {self.form.cleaned_data['incoming_port']}</b>")

            return redirect('device')
        else:
            return super(DeviceCreate, self).get(request, *args, **kwargs)


class DeviceUpdate(PathToCityMixin, PermissionRequiredMixin, TemplateView):
    form = None
    template_name = 'device_edit.html'
    permission_required = ("models_device.change_device")

    def get(self, request, *args, **kwargs):
        self.dev = Device.objects.get(pk = self.kwargs['dev_id'])
        self.form = DeviceForm(instance=self.dev)
        return super(DeviceUpdate, self).get(request, *args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super(DeviceUpdate, self).get_context_data(*args, **kwargs)
        context['device'] = self.dev
        context['form'] = self.form
        return context

    def post(self, request, *args, **kwargs):

intranet/intranet/models_device/templates/all_paginator.html
					{% if page_obj.paginator.num_pages > 1%}
						<nav aria-label="pagunator">
				  			<ul class="pagination pagination-sm">
				  				{% if page_obj.has_previous %}
				  					<li class="page-item"><a class="page-link" href="{% url 'device' %}?page={{ page_obj.previous_page_number }}">Назад</a></li>
				  				{% endif %}

					  			{% for pn in page_obj.paginator.page_range %}
					  				{% if page_obj.number != pn %}
					  					<li class="page-item"><a class="page-link" href="{% url 'device' %}?page={{ pn }}">{{ pn }}</a></li>
					  				{% else %}
					  					<li class="page-item disabled"><a class="page-link" href="#">{{ pn }}</a></li>
					  				{% endif %}
					  			{% endfor %}

					  			{% if page_obj.has_next %}
				  					<li class="page-item"><a class="page-link" href="{% url 'device' %}?page={{ page_obj.next_page_number }}">Вперёд</a></li>
				  				{% endif %}
				  			</ul>
				  		</nav>
				  	{% endif %}

intranet/intranet/models_device/templates/city_paginator.html
					{% if page_obj.paginator.num_pages > 1 %}
						<nav aria-label="pagunator">
				  			<ul class="pagination pagination-sm">
				  				{% if page_obj.has_previous %}
				  					<li class="page-item">
				  						<a class="page-link" 
				  						href="{% url 'dev_list_city' region city.city as url_city %}?page={{ page_obj.previous_page_number }}">Назад</a>
				  					</li>
				  				{% endif %}

					  			{% for pn in page_obj.paginator.page_range %}
					  				{% if page_obj.number != pn %}
					  					<li class="page-item"><a class="page-link" href="{{ url_city }}?page={{ pn }}">{{ pn }}</a></li>
					  				{% else %}
					  					<li class="page-item disabled"><a class="page-link" href="#">{{ pn }}</a></li>
					  				{% endif %}
					  			{% endfor %}

					  			{% if page_obj.has_next %}
				  					<li class="page-item"><a class="page-link" href="{{ url_city }}?page={{ page_obj.next_page_number }}">Вперёд</a></li>
				  				{% endif %}
				  			</ul>
				  		</nav>
				  	{% endif %}

intranet/intranet/models_device/templates/dev_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Список устройств{% endblock %}
{% block head %}

	{% if region %}

{# Если регион выбран, выводим его название #}
		
{# Если город выбран, выводим его название #}
		{% if city %}
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Все регионы</a></li>&nbsp;/&nbsp;
			  	<div class="btn-group">
			  	<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  		<a href="#">{{ region }}</a></li>&nbsp;/&nbsp;
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
					{% for reg in regions %}
								<a class="dropdown-item" href="{% url 'device' %}{{ reg }}/" title="Показать подключения в регионе {{ reg }}">
									{{ reg }}
								</a>
					{% endfor %}
				</div>
</div><div class="btn-group">
  				<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    				<a href="#"><b>{{ city }}</b></a>
  				</li>
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu3">
					{% for city in cities %}
							<a class="dropdown-item" href="{% url 'dev_list_city' region city.city %}" title="Показать подключения в городе {{ city.city }}">{{ city.city }}</a>
					{% endfor %}
				</div>
			</div>
			  </ol>
			</nav>
		{% else %}
{# Если город не выбран, выводим список городов при выбранном регионе #}
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Все регионы</a></li>&nbsp;/&nbsp;
			  	<div class="btn-group">
			  	<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			  		<a href="#"><b>{{ region }}</b></a></li>&nbsp;/&nbsp;
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
					{% for reg in regions %}
								<a class="dropdown-item" href="{% url 'device' %}{{ reg }}/" title="Показать подключения в регионе {{ reg }}">
									{{ reg }}
								</a>
					{% endfor %}
				</div>
</div><div class="btn-group">
  				<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    				<a href="#">Выбрать город</a>
  				</li>
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu3">
					{% for city in cities %}
							<a class="dropdown-item" href="{% url 'dev_list_city' region city.city %}" title="Показать подключения в городе {{ city.city }}">{{ city.city }}</a>
					{% endfor %}
				</div>
			</div>
			  </ol>
			</nav>
		{% endif %}
{# Если регион не выбран, выводим список регионов #}
	{% else %}
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item active">Все регионы</li>
	  				<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    				<a href="#">Выбрать регион</a>
	  				</li>
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
		{% for reg in regions %}
					<a class="dropdown-item" href="{% url 'device' %}{{ reg }}/" title="Показать подключения в регионе {{ reg }}">
						{{ reg }}
					</a>
		{% endfor %}
				</div>
			  </ol>
			</nav>

	{% endif %}
{% endblock %}

{% block main %}
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == "success" %} <div class="alert-success mb-2 w-50">
				{% elif message.tags == "error" %} <div class="alert-danger mb-2 w-50">
				{% else %} <div class="alert-secondary mb-2 w-50">{% endif %}
					{% autoescape off %} {{ message }} {% endautoescape %}
				</div>
			{% endfor %}
		{% endif %}
			<table class="table table-sm table-hover w-50">
			{% for dev in object_list.0 %}
					{% include 'if_search.html' %}
			<tr>
				<td>
					{% if perms.models_device.change_device %}
	          			{% if region %}
						{# Если регион выбран, выводим его название #}
						    
						{# Если город выбран, выводим его название #}
						    {% if city %}
						      <a class="alert-link text-dark" href="{% url 'device_edit_city' region city dev.pk %}" data-toggle="tooltip" data-placement="top" title="Редактировать устройство">
						        <img src="{% static "img/edit.png" %}" width="20" height="20">
						      </a>
						    {% else %}
						      <a class="alert-link text-dark" href="{% url 'device_edit_reg' region dev.pk %}" data-toggle="tooltip" data-placement="top" title="Редактировать устройство">
						        <img src="{% static "img/edit.png" %}" width="20" height="20">
						      </a>
						    {% endif %}

						{# Если регион не выбран #}
						{% else %}
						    <a class="alert-link text-dark" href="{% url 'device_edit' dev.pk %}" data-toggle="tooltip" data-placement="top" title="Редактировать устройство">
						      <img src="{% static "img/edit.png" %}" width="20" height="20">
						    </a>
						{% endif %}
											{% endif %}	
				</td>
				<td>
					<a href="{% url 'connections_on_dev' dev.pk %}" data-toggle="tooltip" data-placement="top" title="Показать подключения на данном устройстве">
						{{ dev.ip }}
					</a>
				<td>
					{{ dev.comment }}
				</td>
				<td>
					{{ dev.model.model }}
				</td>
				<td>
					{% if perms.models_device.delete_device %}
						<a href="" data-toggle="modal" data-target="#deleteModal{{ dev.pk }}" ><img src="{% static "img/delete.png" %}" width="20" height="20"title="Удалить устройство"></a>

						<!-- Modal -->
						<div class="modal fade" id="deleteModal{{ dev.pk }}" tabindex="-1" role="dialog" aria-labelledby="deleteModal{{ dev.pk }}" aria-hidden="true">
						  <div class="modal-dialog modal-dialog-centered" role="document">
						    <div class="modal-content">
						      <div class="modal-header">
						        <h5 class="modal-title" id="deleteModal{{ dev.pk }}">Удаление устройства!!!</h5>
						        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						          <span aria-hidden="true">&times;</span>
						        </button>
						      </div>
						      <div class="modal-body">
						        Вы действительно хотите удалить устройство:<br><b>{{ dev.ip }}&nbsp;({{ dev.model.model }})&nbsp;{{ dev.city.city }}</b><br> и всё, что к нему подключено?
						      </div>
						      <div class="modal-footer">
						        <form action="{% url 'device_delete' %}" method="post">
									<div class="form-group">
										<button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
										{% csrf_token %}
										<input type="hidden" name="device_to_delete" value="{{ dev.pk }}">
										<input class="btn btn-outline-danger" type="submit" name="del_device" value="Удалить">
									</div>
								</form>
						      </div>
						    </div>
						  </div>
						</div>
						
					{% endif %}	
				</td>


				</td>
			</tr>
			{% endfor %}
			</table>
{# Пагинатор #}
			<div class="row">
          		<div class="col-4 p-3">
					{% if city %}
						{% include 'city_paginator.html' %}
					{% elif region %}
						{% include 'region_paginator.html' %}
					{% else %}
						{% include 'all_paginator.html' %}
					{% endif %}
				</div>
			</div>
{% endblock %}

intranet/intranet/models_device/templates/device_add.html
{% extends "base.html" %}

{% block title %}Добаление устройства{% endblock %}
{% block head %}

	{% if region %}
{# Если регион выбран, выводим его название #}
		
{# Если город выбран, выводим его название #}
		{% if city %}
		<nav aria-label="breadcrumb">
		  <ol class="breadcrumb">
		  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Все регионы</a></li>
		    <li class="breadcrumb-item"><a href="{% url 'dev_list_region' region %}">{{ region }}</a></li>
		    <li class="breadcrumb-item active" aria-current="page">{{ city }} </li>
		  </ol>
		</nav>

		{% else %}
{# Если город не выбран, выводим список городов при выбранном регионе #}
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item"><a href="{% url 'device' %}">Все регионы</a></li>
			    <li class="breadcrumb-item active" aria-current="page">{{ region }} </li>
	  				<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    				<a href="#">Выбрать город</a>
	  				</li>
	  				<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
				{% for city in cities %}
						<a class="dropdown-item" href="{% url 'dev_list_city' region city.city %}" title="Показать подключения в городе {{ city.city }}">{{ city.city }}</a>
				{% endfor %}
					</div>
			  </ol>
			</nav>
		{% endif %}
{# Если регион не выбран, выводим список регионов #}
	{% else %}
			<nav aria-label="breadcrumb">
			  <ol class="breadcrumb">
			  	<li class="breadcrumb-item active">Все регионы</li>
	  				<li class="breadcrumb-item dropdown-toggle" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
	    				<a href="#">Выбрать регион</a>
	  				</li>
  				<div class="dropdown-menu" aria-labelledby="dropdownMenu2">
		{% for reg in regions %}
					<a class="dropdown-item" href="{% url 'device' %}{{ reg }}/" title="Показать подключения в регионе {{ reg }}">
						{{ reg }}
					</a>
		{% endfor %}
				</div>
			  </ol>
			</nav>

	{% endif %}
{% endblock %}

{% block main %}
{% load myfilters %}
	<form action="" method="post">
		{% if messages %}
			{% for message in messages %}
				{% if message.tags == "success" %} <div class="alert-success mb-2 w-25">
				{% elif message.tags == "error" %} <div class="alert-danger mb-2 w-25">
				{% else %} <div class="alert-secondary mb-2 w-25">{% endif %}
					{% autoescape off %} {{ message }} {% endautoescape %}
				</div>
			{% endfor %}
		{% endif %}
		<div class="form-group">
			{% csrf_token %}
			{% for f in form %}
				{% if f.errors|length > 0 %}
					<small class="form-text text-muted">{{ f.help_text }}</small>
					{{ f|addclass:'form-control w-25 border border-danger' }}
					<small class="form-text text-muted w-25">
						{{ f.errors }}
					</small>
				{% else %}
					<small class="form-text text-muted">{{ f.help_text }}</small>
					{{ f|addclass:'form-control w-25' }}
				{% endif %}
			{% endfor %}
			<input class="btn btn-outline-secondary" type="submit" name="add_device" value="Добавить">
		</div>
	</form>
{% endblock %}

intranet/intranet/models_device/templates/if_search.html
					{% if request.GET.search %}
					<tr><td colspan="4"></td></tr>
						<tr>
							<td colspan="3">
							{% load myfilters %}
							{{ object_list.1|index:forloop.counter0 }}
							</td>
						</tr>
					{% endif %}